### PR TITLE
Middle assignment Progress

### PR DESCRIPTION
**Pull request by MattWay224**
Matthew Rusakov
m.rusakov@innopolis.university

### CODE REVIEW

**Comment by MattWay224** [comment]
Quick guide:

If you want to see Lo-Fi prototype:
- You may find it in the ui_prototypes
-on the  [link](https://www.figma.com/design/9xsjXswqykG6eQiOmgQD2v/Flutter-Shower-App?node-id=54805-827&node-type=frame&t=ZrCA9J2GeYdGugEU-0)

At the homepage user may start new session or see archive (left top icon) 
here also day streak and profile button at top right, but they does not work

after that user may get the contrast shower session (which can be interrupted) and all sessions will store in the hive

**Comment by timur-harin** [comment]
Good figma!

**Comment by timur-harin** [comment]
And I didnt find OOP usage

**Comment by MattWay224** [comment]
Got you, I will come to you next lab
Yes, I forgot about OOP

**Pull request closed without merging**
